### PR TITLE
Modified prototype MDAnalysis wrapper.

### PR DESCRIPTION
**Pull request by dotsdl**
It can now take both Universes and AtomGroups.

Further addresses #18.

### CODE REVIEW

**Comment by hainm** [comment]
@dotsdl can you add an example to the show_mdanalysis's doc too (since this is API exposed to user).

**Comment by hainm** [comment]
**add** should be **update** to use atomgroup.

**Comment by dotsdl** [comment]
@hainm 

Ah, yeah I was a bit sloppy. I made the fix to the `show_mdanalysis` function. Thanks!

**Comment by hainm** [comment]
@dotsdl This PR does not intend to fix weird bond, right? (just add AtomGroup to constructor).

**Comment by arose** [comment]
Looks good to me, thanks guys!!

**Pull request merged**
