### PR TITLE
add some notebooks

### PR DESCRIPTION
**Pull request by hainm**
only with pytraj. can you try too? @arose

### CODE REVIEW

**Comment by arose** [comment]
I will try later this week, thanks.

**Comment by arose** [comment]
Hope to find time to have a look soon!

**Comment by arose** [comment]
I am thinking of creating a `nglview-notebooks` repository for use with mybinder. I am not sure how much value adding notebooks to this repo has. What do you think, just use a repo for mybinder and link from here to there?

**Comment by hainm** [comment]
> I am thinking of creating a nglview-notebooks repository for use with mybinder.

it's good to me. But we need to add a link to README file so user only a single click to get there. 

related issue: https://github.com/arose/nglview/issues/35

**Comment by hainm** [comment]
@arose can you add snapshot too for notebook too (png file)? widget is not displayed in static nb.

**Pull request closed without merging**
