### PR TITLE
[versioning] fix updating of _version.py for sdist/build_py commands

### PR DESCRIPTION
**Pull request by marscher**
Also upgraded versioneer to 0.18

Note that the current PyPI release (0.6.2.1) has this version string "0+unknown", which makes automatic dependency resolution impossible for pip users.

@cc gph82

### CODE REVIEW

**Comment by hainm** [comment]
thanks. works for me.

**Comment by hainm** [comment]
updated on pypi too.

**Comment by marscher** [comment]
No problem, did you release a new version on pypi then?

**Comment by hainm** [comment]
> updated on pypi too.

**Pull request merged**
