### PR TITLE
remove ngl.js from nglview/js

### PR DESCRIPTION
**Pull request by hainm**
related to: https://github.com/arose/ngl/issues/201

### CODE REVIEW

**Comment by hainm** [comment]
@arose please please keep original (colorful) repr for medium size protein.

This is from 0.9.0-dev.0 ngl

tmpnb_ngl_-_2016-09-19_15 06 41

**Comment by arose** [comment]
> please please keep original (colorful) repr for medium size protein.

the rule is: single polymer chainname -> rainbow colorscheme; otherwise -> chainname colorscheme

**Comment by rgbkrk** [comment]
Wow I love that you all have a dark theme for the viewer.

**Comment by hainm** [comment]
@rgbkrk check this out: https://github.com/dunovank/jupyter-themes

**Comment by rgbkrk** [comment]
Oh. My. Goodness. These are lovely.

nteract has one dark theme, but we could certainly add more.

screen shot 2016-09-19 at 7 59 41 pm

**Pull request closed without merging**
