### PR TITLE
[setup|package] added versioneer to extract version numbers from git

### PR DESCRIPTION
**Pull request by marscher**
Currently (0.4) has no version attribute in the pkg, which makes it hard to determine the real version number in an installed version.

### CODE REVIEW

**Comment by arose** [comment]
Interesting! Thanks! Currently I tag the release with something like "v0.4". after I change the version number in setup.py. I am inclined to go this route will try this later.

What I don't really understand is where the version number will come from in a released package? Is there any VCS info left

**Comment by marscher** [comment]
In a released version the number comes from a minimal
nglview/_version.py (the same unit determines the version number from
the most recent git tag)

**Comment by arose** [comment]
I still don"t understand. Where is the version number (or the info it is derived from) written?

**Comment by marscher** [comment]
There are two main use cases for this:
1. development versioning: Derive the version number from the last release, which is stored in the repository via the git tag. If you are a x commits upstream of last release (tag) you will get a PEP440 compatible development version number like x+y.git-hash.dirty, where y = # commits upstream of x.
2. Easily (just run python setup.py sdist) release a versioned package to the world by just tagging your current state with git tag. During setup.py sdist the version originating from the tag will be statically written to _version.py, which will be contained in your final archive.

**Comment by arose** [comment]
>  During setup.py sdist the version originating from the tag will be statically written to _version.py, which will be contained in your final archive.

Ok, that is what I was after. Thank you!

**Comment by marscher** [comment]
it can also be easily upgraded (done it before in several projects) via versioneer install

**Comment by arose** [comment]
Nice!

screenshot from 2016-02-23 22 37 11

**Comment by hainm** [comment]
Approach in numpy is good too
https://github.com/numpy/numpy/blob/master/setup.py

(I did that for pytraj)

**Comment by arose** [comment]
> Approach in numpy is good too

Oh, thanks, so many options. I would go with Versioneer now as  have it already working.

**Comment by arose** [comment]
Thanks @marscher!

**Pull request merged**
