### PR TITLE
Alias repr: add_method_name

### PR DESCRIPTION
**Pull request by hainm**
```python
view.add_cartoon(selection='all', color='residueindex')
view.add_surface(selection='not water', color='residueindex')
```

and so on. Need you guys to manually test in notebook. (I've tested myself and seems fine).

address https://github.com/arose/nglview/issues/45

Also adding a script to easily update in future.

### CODE REVIEW

**Comment by jbarnoud** [comment]
Couldn't the functions be created at runtime from the `reprs` dictionary rather than having an external script that edits `__init__.py`?

**Comment by hainm** [comment]
@jbarnoud yes :D

**Comment by hainm** [comment]
@arose I will go ahead to merge this PR next Monday if you don't have objection.

**Comment by arose** [comment]
I like @jbarnoud suggestion. Maybe just something like this `for name in repr_names: self[ "add_" + name ] = def ...` in the constructor.

**Comment by hainm** [comment]
yeah, I will update it.

**Comment by hainm** [comment]
ok, after playing with dynamic function, I gave up. It's too complicated for simple code.

I tried [this](https://github.com/hainm/nglview/blob/5cbdd42e25081ff96dfd413049b308ad55fc4491/nglview/__init__.py#L369-L402) and got

```bash
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-7d8b37bbcc6c> in <module>()
----> 1 view.add_backbone()

TypeError: _add_backbone() missing 1 required positional argument: 'self'
```

If anyone would like to try, more than welcome. :D 

```python
        # dynamically create add_{method}
        _repr_names  = [
                ('point', 'point'),
                ('line', 'line'),
                ('cartoon', 'cartoon'),
                ('licorice', 'licorice'),
                ('ribbon', 'ribbon'),
                ('surface', 'surface'),
                ('trace', 'trace'),
                ('tube', 'tube'),
                ('label', 'label'),
                ('backbone', 'backbone'),
                ('ball_and_stick', 'ball+stick'),
                ('contact', 'contact'),
                ('crossing', 'crossing'),
                ('helixorient', 'helixorient'),
                ('hyperball', 'hyperball'),
                ('rocket', 'rocket'),
                ('rope', 'rope'),
                ('simplified_base', 'base'),
                ]
        
        _template = """
        def _add_{method}(self, selection='all', **kwd):
            '''shortcut for self.add_representation("...", *args, **kwd)
            '''
            self.add_representation('{representation}', selection, **kwd)
        """.strip()
        
        self._func_dict = {}
        for _rep in _repr_names:
            exec(_template.format(method=_rep[0], representation=_rep[1]),
                self._func_dict)
            setattr(self, "add_{}".format(_rep[0]), self._func_dict['_add_' + _rep[0]])
```

**Comment by hainm** [comment]
this does not work either: https://github.com/hainm/nglview/commit/fbfc9c1fba6f351688619357854b85c91ca57319

```python
view.add_cartoon(color='red')
``` does not change anything.

**Comment by jbarnoud** [comment]
I can give it a try. But not before the end of the week.

**Comment by hainm** [comment]
> I can give it a try. But not before the end of the week. 

@jbarnoud any update on this? thanks.

**Comment by hainm** [comment]
close this PR in favor of https://github.com/arose/nglview/pull/57

**Pull request closed without merging**
