### PR TITLE
ADD: caching for smooth trajectory play

### PR DESCRIPTION
**Pull request by hainm**
5-10 times faster for sending.

To do

Syntax
=====
```python
view = nv.show_pytraj(traj)
view.caching() # sending all coordinates to Javascript by decoding coords to base64 string
# view.coordinates won't be updated if caching

view.uncaching() #
# view.coordinates will be synced (but still slow, not good for viewing heavy trajectory)
```

caching

Support
======

-[x] pytraj
- [x] mdtraj
- [x] MDAnalysis
- [x] ParmEd

Question
========

- [x] What should I do with `view.coordinates`. In this PR, it returns base64 string (synced with JS side): should return ndarray

should we make it private (change to `_coordinates`) and add

```python
@property
def coordinates(self):
    (return numpy array)
```

- [x] How to decode base64 back to numpy array? easy.

MIGRATION
==========

- [x] remove `get_coordinates_list`: We don't sync this anymore. Should use base64 or bytes (later)

ADD
====
- [x] get_coordinates(index): coords for a single frame
- [x] get_coordinates_dict: dict of coords for all frames
- [x] unit tests

### CODE REVIEW

**Comment by hainm** [comment]
thanks to **chemview** .

**Comment by hainm** [comment]
only finished work for pytraj, but just need to copy and paste to other backend.

**Comment by arose** [comment]
Please also look at https://github.com/vispy/vispy/blob/master/vispy/html/static/js/webgl-backend.js#L96-L106 and https://github.com/vispy/vispy/blob/f6c0e03e36ec402f1f3a1fb5909dc09575b4fb69/vispy/app/backends/ipython/_widget.py#L75-L91

It should be possible to send the data as binary, no need for base64 encoding/decoding.

**Comment by hainm** [comment]
@arose how's about the speed comparison?

from my benchmark, sending numpy bytes is still slower than sending base64. https://github.com/arose/nglview/issues/58

So I guess I am misunderstood the concept of sending binary.
```python
view.send(base64_data)
view.send(numpy_bytes)
```

What is `buffers` used for?

**Comment by arose** [comment]
I suspect that `view.send(numpy_bytes)` sends a JSON message with an array holding all those bytes (`[2, 3, 4, 2, 3, 6, ...]`), whereas `view.send(base64_data)` sends a JSON with a string (`"base64..."`). Serializing a string is much faster than serializing an array, which is where the speed gain comes from.

> What is buffers used for?

I don't know exactly, but I assume it refers the binary data that is in JavaScript stored in an [`ArrayBuffer`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer).

**Comment by hainm** [comment]
Thanks. I need to read about that 'buffer', if we can send binary via that. Using numpy ravel().tobytes() is very fast.

**Comment by arose** [comment]
> Thanks. I need to read about that 'buffer', if we can send binary via that. Using numpy ravel().tobytes() is very fast.

Yes. If you install https://github.com/arose/mdsrv locally you should be able play a system with 50.000 atoms without much lag. The server sends the data as binary, frame by frame. The same speed should be possible with Jupyter.

**Comment by hainm** [comment]
now I know how to correctly send buffer

```python
view.send("hi", buffers=[traj.xyz])
```

this is 10 times faster (and less memory) than sending base64.

Kool.

**Comment by hainm** [comment]
so the question is
- how to convert buffer to Float32Array
- Should NGL have option to read buffer directly to avoid copying twice?

**Comment by arose** [comment]
> how to convert buffer to Float32Array

```JavaScript
new Float32Array( buffer );  // assuming buffer contains an array of 32-bit floats
```

> Should NGL have option to read buffer directly to avoid copying twice?

Like this should be fine:

```JavaScript
var coords = new Float32Array( buffer );
component.structure.updatePosition( coords );
component.updateRepresentations( { "position": true } );
```

**Comment by hainm** [comment]
thanks. So I think that's exactly I've been trying.

But now sure why lenght of the buffer reduced a bit, so `new Float32Array(buffer)` return []

python

```python
print(len(xyz_bytes)) # get 133128
view.send({'type': 'coords', 'buffers': xyz_bytes})
```

JS
```
               console.log( msg.buffers.length ); # get 131702
               var coords = new Float32Array( msg.buffer );
               console.log( coords ); # get []
```

This is the only thing I am stuck.

**Comment by hainm** [comment]
Don't know the solution yet. But with the `caching` implementation in this PR, I am able to view 6K frames of > 8 atoms system in our supercomputer cluster, where X11 is not allowed (meaning no VMD).
The trajectory after being cached is played very smooth (just like using VMD in my local computer). So I am very please with NGLView now. lol.

**Comment by hainm** [comment]
a tutorial with pytraj+nglview is made for AMBER16 (will be released in next few weeks): http://ambermd.org/tutorials/analysis/#pytraj

Hopefully we can have nice movie to show.

**Comment by hainm** [comment]
merged. Please read all the logs in my 1st post.

- fast viewing if using cache
- support pytraj, mdtraj, MDA, parmed
- add 9 tests
- check code coverage (80% in PY2)

**Comment by hainm** [comment]
related binary stuff: https://github.com/rgbkrk/bitjet/blob/master/bitjet/bitjet.py

**Comment by hainm** [comment]
related byte loss: https://github.com/ipython/ipywidgets/issues/228

**Pull request merged**
