### PR TITLE
distance repr

### PR DESCRIPTION
**Pull request by hainm**
not yet accept int array-like

distance_repr

### CODE REVIEW

**Comment by gph82** [comment]
IDK if it's better to open an issue, but this PR is where I found the add_distance call best documented (otherwise I'm working with this doc (http://arose.github.io/ngl/api//global.html#DistanceRepresentationParameters). 

Any ideas of why this is not showing the distance?
snap16

**Comment by hainm** [comment]
From my 1st comment:
> not yet accept int array-like

@gph82 can you try to reproduce my example above first? 

I think `atom_pair` is a list of list. (my fault for not writing a goo docs).

**Comment by gph82** [comment]
Gold pöint!  I'm afk now, will try  later. Thanks!

**Comment by gph82** [comment]
yupp, that did the trick, thanks!

**Pull request merged**
