### PR TITLE
Rotate speed

### PR DESCRIPTION
**Pull request by hainm**

### CODE REVIEW

**Comment by arose** [comment]
looks good, thanks!

**Comment by arose** [comment]
A more general solution would be to have a parameter dict as a traitlet on the Python side and feed it into `stage.setParameters` in JavaScrict. That would make the current `fog` and `rotateSpeed` properties obsolete.

**Comment by hainm** [comment]
sounds better. :+1:

**Comment by hainm** [comment]
by the way, ipywidgets has pretty good noteboks to look at.

https://github.com/ipython/ipywidgets/tree/master/examples/notebooks

**Comment by arose** [comment]
Thanks for the link. Feel free to implement the more general approach.

**Comment by hainm** [comment]
@arose  do you mean like this? (given I am not good at JS)

```bash
--- a/nglview/html/static/widget_ngl.js
+++ b/nglview/html/static/widget_ngl.js
@@ -77,6 +77,10 @@ define( [
                 // init rotation speed?
                 this.model.on( "change:rotate_speed", this.rotateSpeedChanged, this );

+                // init parameters
+                // parameters is a dict
+                this.model.on( "change:parameters", this.parametersChanged, this );
+
                 // init NGL stage
                 NGL.useWorker = false;
                 this.stage = new NGL.Stage();
@@ -250,6 +254,11 @@ define( [
             this.stage.viewer.controls.rotateSpeed = rotateSpeed;
         },

+        parametersChanged: function(){
+            var pars = this.model.get( "parameters" );
+            this.stage.setParameters(pars);
+        },
+
     } );

     manager.WidgetManager.register_widget_view( 'NGLView', NGLView );
```

**Comment by arose** [comment]
yeah, seems correct, though I always call it `params` not `pars`. Also, I just updated the ngl version in nglview, which was somewhat outdated and might be needed for it to fully work.

**Comment by hainm** [comment]
Thanks.

Can you add an example here about the usage? I've try to change things but seems not working for me. I guess just like updating list of dict (like representations) or dict? Right. 

I will try to read your js code and follow code style.

**Comment by arose** [comment]
have you tried it with the just updated nglview version?

A dict traitlet from Python should translate nicely to a plain object in JavaScript. Just as in the code for the representations.

**Comment by hainm** [comment]
> have you tried it with the just updated nglview version?

not yet.

> A dict traitlet from Python should translate nicely to a plain object in JavaScript. Just as in the code for the representations.

:+1:

**Comment by hainm** [comment]
successfully. :+1: :+1:

**Pull request merged**
