### PR TITLE
initial attempt to add dirty nglview cmd

### PR DESCRIPTION
**Pull request by hainm**
use `pytraj`.

(still slow but it's better than nothing).

### CODE REVIEW

**Comment by arose** [comment]
nice idea! I have something similar in mdsrv (https://github.com/arose/mdsrv/blob/master/mdsrv/mdsrv.py#L359-L380) but that is not using jupyter...

**Comment by hainm** [comment]
cool. Let's see if I could steal anything from it.

**Comment by hainm** [comment]
cool. Let's see if I could steal anything from it.

**Comment by hainm** [comment]
mdsrv is very cool and is exactly I want to spend time with.

**Pull request merged**
