### PR TITLE
FIX Color scheme for embeding

### PR DESCRIPTION
**Pull request by hainm**
#802

### CODE REVIEW

**Comment by jbloom** [comment]
@hainm: I was wondering if relatively soon you might be able to tag a new minor version with the updated color scheme with the change to add labels to the `_ColorScheme` that you made in this commit? I'm trying to create a [mybinder](https://mybinder.org/) instance that uses `nglview`, and I'm having trouble figuring out how to configure the environment to use a version of `nglview` that isn't version tagged. 

Certainly a new version on PyPI makes it easy, but I think even just having a tagged minor version on GitHub is adequate to enable this.

**Comment by hainm** [comment]
I can do it tonight (to make a git tag only and only work with notebook,
not lab). Cheers

Hai

**Comment by hainm** [comment]
@jan-janssen  v2.0.0 should be available on github and pypi now.

> I'm having trouble figuring out how to configure the environment to use a version of nglview that isn't version tagged.

You can also use git commit hash.
```
cd nglview
git checkout commit_id_you_want
python setup.py install
```

PS: We pump to major version because we are dropping python 2.

**Comment by jan-janssen** [comment]
@jbloom I also build a mybinder environment with NGLview, you can find my configuration here https://github.com/pyiron/pyiron/tree/master/binder

**Pull request merged**
