### PR TITLE
fixed docs on show_mdanalysis

### PR DESCRIPTION
**Pull request by richardjgowers**
currently not turned into code-like docs: http://nglviewer.org/nglview/latest/api.html#nglview.show_mdanalysis

### CODE REVIEW

**Comment by hainm** [comment]
hi @richardjgowers, it was my intention to remove the `>>>` to avoid testing mdanalysis docs in unittest. Can you update the unittest to skip mdanalysis?

```
=================================== FAILURES ===================================
___________________________ test_nglview_show_module ___________________________
    @unittest.skipUnless(PY3, 'doctest with py3 only')
    def test_nglview_show_module():
        """
        """
>       assert not get_total_errors([show])
E       AssertionError: assert not 4
E        +  where 4 = get_total_errors([<module 'nglview.show' from '/home/travis/miniconda/envs/myenv/lib/python3.6/site-packages/nglview/show.py'>])
```

**Comment by hainm** [comment]
oh, please just use this format
```python
    >>> import iotbx.pdb
    ... x = iotbx.pdb.hierarchy.input('file.pdb')
    ... mol = x.construct_hierarchy()
    ... view = nglview.show_iotbx(hi)
    ... view # doctest: +SKIP
```
http://nglviewer.org/nglview/latest/api.html#nglview.show_iotbx

**Comment by richardjgowers** [comment]
I thought the ... was for line continuations, not multiple lines?

**Comment by hainm** [comment]
> I thought the ... was for line continuations

that's correct. I used that to only use a single "# doctest: +SKIP". If you want multiple lines, you might need to add multiple "# doctest: +SKIP" too. Both ways are fine with me.

**Comment by hainm** [comment]
thanks @richardjgowers.

**Pull request merged**
