### PR TITLE
just try to install on travis

### PR DESCRIPTION
**Pull request by hainm**
start working on unit test (still don't know how to run notebook with widget on travis yet). This PR try to install nglview with different Python version (2.7, 3.4, 3.5) and linux, osx.

travis: https://travis-ci.org/hainm/nglview/builds/110883044

### CODE REVIEW

**Comment by arose** [comment]
This is this ready for testing, right?

**Comment by hainm** [comment]
You can merge this PR now. Currently just check if nglview is installable for different python version. 

I will submit another PR for teating.

Can you update the title too (using phone now).

**Comment by marscher** [comment]
one could use a virtual framebuffer X11 server to perform gui tests.

**Comment by arose** [comment]
Thanks @hainm it seems to work. Added badge to readme.

**Pull request merged**
