### PR TITLE
ADD Custom color scheme API

### PR DESCRIPTION
**Pull request by hainm**

### CODE REVIEW

**Comment by sperezconesa** [comment]
Hello, 
Could you give an example function in which a color scale and not discrete colors are used? Thank you!
Best,
Sergio

**Comment by hainm** [comment]
@sperezconesa I personally don't know "how". @arose Do you have any suggestion? thanks.

**Comment by seanrjohnson** [comment]
Hi,

I can't get this example to work in Colab (works in local notebooks though).

Is there a way to do custom coloring by residue in colab?

Here is the code I tried.

Output from colab was a completely white structure
Output from local notebook was as shown above, with the blue section.

Cell 1
```
!pip install -q nglview pytraj
from google.colab import output
output.enable_custom_widget_manager()
```

Cell 2
```
import nglview as nv
from nglview.color import ColormakerRegistry

cm = ColormakerRegistry
cm.add_selection_scheme("awesome",
        [['blue', '1-10']])

v0 = nv.demo(default=False)
v0.center()
v0.add_cartoon(color='awesome')
v0
```

**Comment by hainm** [comment]
> Hi,
> 
> I can't get this example to work in Colab (works in local notebooks though).
> 
> Is there a way to do custom coloring by residue in colab?
> 
> Here is the code I tried.
> 
> Output from colab was a completely white structure Output from local notebook was as shown above, with the blue section.
> 
> Cell 1
> 
> ```
> !pip install -q nglview pytraj
> from google.colab import output
> output.enable_custom_widget_manager()
> ```
> 
> Cell 2
> 
> ```
> import nglview as nv
> from nglview.color import ColormakerRegistry
> 
> cm = ColormakerRegistry
> cm.add_selection_scheme("awesome",
>         [['blue', '1-10']])
> 
> v0 = nv.demo(default=False)
> v0.center()
> v0.add_cartoon(color='awesome')
> v0
> ```

hi @seanrjohnson, there is nothing we can do about colab besides waiting for google to improve it.

**Comment by wangm23456** [comment]
This seems to be the only effective way at present.
https://github.com/nglviewer/nglview/blob/a0b53a4a26f1ea278a14910e75881d73622cebfe/nglview/tests/test_widget.py#L442

**Comment by mretier** [comment]
Is this also supported for surfaces? I can't seem to get it to work.
`view.add_representation('surface', component=2, color='awesome')`

**Comment by hainm** [comment]
@mretier would you mind ask something like 'is is possible to custom color of the surface repr or not?', in `NGL` repo: https://github.com/nglviewer/ngl

cheers.

**Comment by hainm** [comment]
thanks @mretier

**Comment by mretier** [comment]
@hainm please check out the response in the above mentioned thread. It appears to be possible.

**Comment by mretier** [comment]
@hainm yes, it was my intention in this specific case. When using the same code to apply to the cartoon representation it worked

**Comment by hainm** [comment]
@mretier I've made a comment here, is that similar to what you're trying? https://github.com/nglviewer/ngl/issues/1005#issuecomment-1845971098

**Comment by mretier** [comment]
@hainm thanks for the comment. I was able to reproduce your results. Howevever, it does not seem to work with my own code that's a bit different. It's not clear to me why it wouldn't work in my case:

```
import nglview as nv
from Bio.PDB import *
```

```
# new cell
parser = PDBParser()
# load Zymomonas mobilis alcohol dehydrogenase
Zmadh = parser.get_structure('3OWO', './3owo_Zmadh.pdb')
# remove second dimer structure
Zmadh[0].detach_child('C')
Zmadh[0].detach_child('D')
```

**Comment by hainm** [comment]
May be your atom selection is not right?

Hai

**Comment by hainm** [comment]
Can you please provide exact code + data so I can reproduce your issue?

Hai

**Comment by mretier** [comment]
@hainm thanks for your effort, the above code should be fully functional. For your convenience I attached the full code here as well as the .pdb file.
[code and structure.zip](https://github.com/nglviewer/nglview/files/13717554/code.and.structure.zip)

**Comment by hainm** [comment]
I could reproduce the issue with your code + file. Let me play more with it. Cheers.

**Pull request merged**
