### PR TITLE
Ngl update to 0.7

### PR DESCRIPTION
**Pull request by arose**

### CODE REVIEW

**Comment by arose** [comment]
ok, please give it a try

**Comment by hainm** [comment]
I am trying. 

First question.

- does 0.7 NOT support for adding surface for waters? 

```python
import pytraj as pt
import nglview as nv

traj = pt.datafiles.load_tz2_ortho()[:].autoimage()

view = nv.show_pytraj(traj)
view

view._clear_repr()
view.add_cartoon()
view.add_surface(opacity=0.3)
```

**Comment by arose** [comment]
I see, try `view.add_surface(opacity=0.3, useWorker=False)`

**Comment by hainm** [comment]
`useWorker=False` does the trick. thx.

`export_image.ipynb` does not work anymore. I guess NGL changes the method name. I will look further.

**Comment by arose** [comment]
> export_image.ipynb does not work anymore. I guess NGL changes the method name. I will look further.

```JavaScript
stage.makeImage( {
    factor: 1,
    antialias: true,
    trim: false,
    transparent: false
} ).then( function( blob ){
    NGL.download( blob, "screenshot.png" );
} );
```

**Comment by arose** [comment]
> useWorker=False does the trick. thx.

can you enforce that in code?

**Comment by hainm** [comment]
> can you enforce that in code?

yes. Will make PR.

So I just tested all the notebooks. There are only two mentioned issues.

**Comment by hainm** [comment]
change `exportImage` to `makeImage` does not work too. There is no error message in console but nothing shows up.

**Comment by hainm** [comment]
oh I see. NGL passes `params` object rather unpacking argument.

**Comment by hainm** [comment]
@arose  I need you to look at export_image.ipynb. Doesn't work after trying.

I passed `Object {transparent: false, factor: 1, antialias: true, trim: false}` to `stage.makeImage` but nothing shows up although the screen flashed.

**Comment by hainm** [comment]
should try my PR: https://github.com/arose/nglview/pull/125

**Comment by hainm** [comment]
Damn, I did not use 'download' method. Will try.

**Comment by hainm** [comment]
happy merging.

Summary
--------------

- update NGL code
- fix `add_surface` repr
- fix `export_image` and change its name to `download_image`.
```python
view.download_image(filename, **params)
```
- add test for `simpletraj`

**Pull request merged**
