### PR TITLE
added Trajectory and show_ wrappers for HTMD

### PR DESCRIPTION
**Pull request by stefdoerr**
Tested it locally and it seems to work fine. Take a quick look if you can if I forgot something.

### CODE REVIEW

**Comment by hainm** [comment]
Thanks.

Is it possible to add a test on travis? 

Please have a look at nglview/tests/test_widgets.py (not remember exactly)

**Comment by hainm** [comment]
Can you update README.md file too?

**Comment by stefdoerr** [comment]
Ok fixed everything you said. I don't see however who calls the test functions.

**Comment by hainm** [comment]
- Can `htmd` run on travis? If yes, we should install and run its test [https://github.com/arose/nglview/blob/master/devtools/travis-ci/setup_env.sh]

**Comment by hainm** [comment]
per running test: we are using `pytest`

You can run your test by `py.test -k test_show_htmd`, run all test by `py.test .`

**Comment by hainm** [comment]
See also: https://github.com/arose/nglview/blob/master/devtools/travis-ci/run_tests.sh

**Comment by hainm** [comment]
looking `htmd` travis, seems lots of dependence. So I think I go ahead merging this without "requiring" more. thanks.

**Comment by stefdoerr** [comment]
yeah we have a few dependencies. Great, thanks for integrating it :)

**Comment by arose** [comment]
> looking htmd travis, seems lots of dependencies. So I think I go ahead merging this without "requiring" more. thanks.

yeah, the tests already take a long time to run on travis.

**Comment by hainm** [comment]
@arose I don't mind about long time. 10-20 minutes is fine. I really care about code coverage. (just dropped from 95% to 94% :D).

**Pull request merged**
