### PR TITLE
update notebook for rdkit

### PR DESCRIPTION
**Pull request by hainm**
It turns out that I added support for `rdkit` via [ParmEd](https://github.com/ParmEd/ParmEd) a while ago. So `nglview` is supporting `rkdit`.

I made this notebook after reading @dkoes and @greglandrum  [notebooks](http://nbviewer.jupyter.org/github/greglandrum/rdkit_blog/blob/master/notebooks/Trying%20py3Dmol.ipynb)

 with [3Dmol](https://github.com/3dmol/3Dmol.js) and [rdkit](https://github.com/rdkit/rdkit).

rdkit

### CODE REVIEW

**Comment by hainm** [comment]
this partiall address https://github.com/arose/nglview/issues/136. For now, user should visualize rdkit via converting to ParmEd' object (with two lines of code)

**Comment by hainm** [comment]
for now, it's good to support rdkit via ParmEd (with two lines of codes).

cc @arose, @swails

**Comment by greglandrum** [comment]
Looks cool! I assume from the screenshot that the slider at the bottom switches between the molecule's conformations?

**Comment by hainm** [comment]
Yes.

**Pull request merged**
