### PR TITLE
add show_parmed

### PR DESCRIPTION
**Pull request by hainm**
ParmEd: https://github.com/ParmEd/ParmEd

Example:
picture1

Buzz @swails.

### CODE REVIEW

**Comment by swails** [comment]
Cool

**Comment by hainm** [comment]
@arose I will go ahead to merge this PR next Monday if you don't have objection.

**Comment by arose** [comment]
Looks good, just one thing, please add ParmEd to `extras_require` in setup.py, thanks!

**Comment by hainm** [comment]
ok. I will update.

**Comment by hainm** [comment]
updated.

**Pull request merged**
