### PR TITLE
color by residues

### PR DESCRIPTION
**Pull request by hainm**
related to #491 

Just demo.

### CODE REVIEW

**Comment by hainm** [comment]
```python
import nglview as nv

view = nv.demo()
view

# use hex values for now.
colors = ['0x0000FF', '0xFF0000'] * 1000 # for 2000 residues.
view._set_color_by_residue(colors, component_index=0, repr_index=0)
```

**Comment by hainm** [comment]
colors

**Comment by arose** [comment]
nice, looks good!

**Comment by hainm** [comment]
@arose seems not working properly. I got black if not using red/green/blue colors.

What should I update here?
```javascript
    setColorByResidue: function(colors, component_index, repr_index){
        var repr = this.stage.compList[component_index].reprList[repr_index];
        var schemeId = NGL.ColorMakerRegistry.addScheme(function(params){
            this.atomColor = function(atom){
                 var color = colors[atom.residueIndex];
                 return color
            };
        });
        repr.setColor(schemeId);
    },
```

colors

**Comment by arose** [comment]
The colors array has to be a list of integers: `[ 0xedd1cb, 0xedd1cb, 0xedd1ca, 0xedd0ca ]`

**Comment by hainm** [comment]
I see. This is the output from seaborn
```python
import seaborn as sns

colors = sns.cubehelix_palette(400).as_hex()
colors[:4]
['#edd1cb', '#edd1cb', '#edd0ca', '#edd0ca']
```

**Comment by hainm** [comment]
replace '#' by '0x'.

```python
colors = [c.replace('#', '0x') for c in sns.cubehelix_palette(400).as_hex()]
```

**Comment by arose** [comment]
no, that are still strings `0xFF00FF` is the way to write integers as hex numbers in Python (not, no quotes).

**Comment by hainm** [comment]
but it (string) actually 'works' :D I guess this happen since python list will be serialized before being sent to  JS.

**Comment by arose** [comment]
:-)

**Comment by surgebiswas** [comment]
I copied and pasted the demo code exactly as is above and it does not work.  The protein remains blue for me. Has there been any updates to the source code since the discussion above?

**Comment by hainm** [comment]
@surgebiswas which version you are using? If you are using the version after this commit, can you open a new issue to keep track? thanks.

**Pull request merged**
